### ISSUE TITLE
Commit rights for maoo

### ISSUE THREAD

**Issue by maoo** [Alfresco/alfresco-indexer#17]
Not sure if I've access, but I'd like to confirm (from anyone is the administrator of this project) to grant me (@maoo) commit rights, so that I can keep on merging PRs and continue to cover my role in the Apache ManifoldCF project.

Thanks!

**Comment by maoo** [comment]
Got it, thank you!

**Comment by bmlong137** [comment]
I was not able to grant access (not an admin).  So someone else got it for you...

________________________________
